name: Selenium Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+" | head -n 1)
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" || curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          if [ -z "$DRIVER_VERSION" ]; then
            echo "Erro ao obter a versão do ChromeDriver"
            exit 1
          fi
          wget -N "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip" -P /tmp/
          unzip -o /tmp/chromedriver_linux64.zip -d /tmp/
          sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version  # Verifica a versão do ChromeDriver instalada

      - name: Run Tests with Maven
        run: mvn clean test -Dbrowser=chrome