name: Selenium Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install Google Chrome and ChromeDriver
        run: |
          CHROME_VERSION="129.0.6668.100"  # Substitua pela versão desejada

          wget -N "https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chrome-linux64.zip" -P /tmp/
          unzip -o /tmp/chrome-linux64.zip -d /tmp/
          sudo mv /tmp/chrome-linux64 /opt/google/chrome
          sudo ln -s /opt/google/chrome/chrome /usr/bin/google-chrome

          wget -N "https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/chromedriver-linux64.zip" -P /tmp/
          unzip -o /tmp/chromedriver-linux64.zip -d /tmp/
          sudo mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

          google-chrome --version
          chromedriver --version

      - name: Run Tests with Maven
        run: mvn clean test -Dbrowser=chrome
